#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QVariant>
#include <QMainWindow>
#include "canvas.h"

namespace Ui {
    class MainWindow;
}

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    explicit MainWindow(QWidget *parent = 0);
    ~MainWindow();

private:
    // EXCEPTION: 'ui' member which is auto-generated by Qt. DO NOT RENAME!
    Ui::MainWindow *ui;

    Canvas *m_canvas;
};

#endif // MAINWINDOW_H
